# Generated by Django 5.2.11 on 2026-03-29 20:40

import sacd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=sacd.models.user_directory_path)),
            ],
        ),
    ]
